apiVersion: v1
kind: Service
metadata:
  name: cast-backend
  labels:
    app: cast-app
    name: backend-service
spec:
  selector:
    app: cast-app
    name: cast-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-backend
spec:
  selector:
    matchLabels:
      app: cast-app
  template:
    metadata:
      labels:
        app: cast-app
        name: cast-backend
    spec:
      containers:
        - name: cast-backend
          image: cast23.lol/cast-backend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: IS_STAGING
              value: "true"
      imagePullSecrets:
        - name: registry-credentials