apiVersion: v1
kind: Service
metadata:
  name: cast-database
  labels:
    app: cast-app
    name: database-service
spec:
  selector:
    name: cast-database
    app: cast-app
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-database
spec:
  selector:
    matchLabels:
      app: cast-app
      name: cast-database
  template:
    metadata:
      labels:
        app: cast-app
        name: cast-database
    spec:
      containers:
        - name: cast-database
          image: postgres:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              value: username
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: cast
          ports:
            - containerPort: 5432