apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: cast-app
    name: frontend-service
    tier: frontend
spec:
  selector:
    app: cast-app
    name: cast-frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-frontend
spec:
  selector:
    matchLabels:
      app: cast-app
  template:
    metadata:
      labels:
        app: cast-app
        name: cast-frontend
    spec:
      containers:
        - name: cast-frontend
          image: cast23.lol/cast-frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-credentials